name: shulan_edu
description: A new Flutter application.
version: 1.0.0+1



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter

#    flutter_inapp_purchase: ^3.0.1
    flutter_verification_box: ^1.0.4
    flutter_qr_reader: ^1.0.3
    pull_to_refresh: ^1.6.5
    flutter_rating_bar: ^3.2.0

    common_plugin:
      git:
        url: https://devops.rubikstack.com:10080/surface/common_plugin.git
        ref: flutter-2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
